# SMPL:
#   MODEL_PATH: _DATA/models
#   GENDER: neutral
#   MODEL_TYPE: smpl
#   NUM_BODY_JOINTS: 23
#   JOINT_REGRESSOR_H36M: _DATA/J_regressor_h36m.npy
#   JOINT_REGRESSOR_EXTRA: _DATA/SMPL_to_J19.pkl
#   TEXTURE: _DATA/texture.npz
# MODEL:
#   IMAGE_SIZE: 256
#   SMPL_HEAD:
#       TYPE: basic
#       POOL: max
#       SMPL_MEAN_PARAMS: _DATA/smpl_mean_params.npz
#       IN_CHANNELS: 2048
#   BACKBONE:
#     TYPE: resnet
#     NUM_LAYERS: 50
#   TRANSFORMER:
#     HEADS: 1
#     LAYERS: 1
#     BOX_FEATS: 6
# EXTRA:
#   FOCAL_LENGTH: 5000


SMPL:
  MODEL_PATH: _DATA/models
  GENDER: neutral
  MODEL_TYPE: smpl
  NUM_BODY_JOINTS: 23
  JOINT_REGRESSOR_H36M: _DATA/J_regressor_h36m.npy
  JOINT_REGRESSOR_EXTRA: _DATA/SMPL_to_J19.pkl
  TEXTURE: _DATA/texture.npz
MODEL:
  IMAGE_SIZE: 256
  SMPL_HEAD:
      TYPE: basic
      POOL: max
      SMPL_MEAN_PARAMS: _DATA/smpl_mean_params.npz
      IN_CHANNELS: 2048
  BACKBONE:
    TYPE: resnet
    NUM_LAYERS: 50
  TRANSFORMER:
    HEADS: 1
    LAYERS: 1
    BOX_FEATS: 6
EXTRA:
  FOCAL_LENGTH: 5000
